# Generated by Django 2.1.5 on 2019-02-11 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appname', models.CharField(max_length=264)),
                ('developername', models.CharField(max_length=264)),
                ('date', models.CharField(max_length=264)),
                ('version', models.CharField(max_length=264)),
                ('size', models.CharField(max_length=264)),
                ('description', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('email', models.CharField(max_length=264, unique=True)),
                ('password', models.CharField(max_length=264)),
                ('confirm_password', models.CharField(max_length=264)),
                ('dob', models.CharField(max_length=264)),
                ('ph', models.CharField(max_length=264)),
                ('occupation', models.CharField(max_length=264)),
                ('intitution', models.CharField(max_length=264)),
                ('gender', models.CharField(max_length=264)),
                ('about', models.CharField(max_length=264)),
            ],
        ),
        migrations.RemoveField(
            model_name='accessrecord',
            name='name',
        ),
        migrations.RemoveField(
            model_name='webpage',
            name='topic',
        ),
        migrations.DeleteModel(
            name='AccessRecord',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.DeleteModel(
            name='WebPage',
        ),
        migrations.AddField(
            model_name='appprofile',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.SignUp'),
        ),
    ]
