# Generated by Django 2.1.5 on 2019-02-13 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20190211_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('email', models.CharField(max_length=264, unique=True)),
                ('catagory', models.CharField(max_length=264)),
                ('department', models.CharField(max_length=264)),
                ('dept_id', models.CharField(max_length=264)),
                ('password', models.CharField(max_length=264)),
                ('confirm_password', models.CharField(max_length=264)),
                ('phone_no', models.CharField(max_length=264)),
                ('about', models.CharField(max_length=264)),
            ],
        ),
        migrations.RemoveField(
            model_name='appprofile',
            name='signup',
        ),
        migrations.DeleteModel(
            name='SignUp',
        ),
        migrations.AddField(
            model_name='appprofile',
            name='Foreien_Key_From_SignUP',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='first_app.Profile'),
            preserve_default=False,
        ),
    ]
