# Generated by Django 2.1.5 on 2019-02-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_auto_20190213_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='App_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=100, unique=True)),
                ('developer', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('apklocation', models.CharField(max_length=100)),
                ('imagelocation', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='appprofile',
            name='Foreien_Key_From_SignUP',
        ),
        migrations.DeleteModel(
            name='AppProfile',
        ),
    ]
