# Generated by Django 2.1.5 on 2019-02-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_auto_20190217_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_profile',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
