# Generated by Django 2.1.5 on 2019-02-18 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_auto_20190217_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyWishList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=264, unique=True)),
                ('app_name', models.CharField(max_length=264)),
            ],
        ),
    ]
