# Generated by Django 2.1.5 on 2019-02-18 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_mywishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mywishlist',
            name='email',
            field=models.CharField(max_length=264),
        ),
    ]
